name: Publish website

on:
  push:
    branches: [main]
  pull_request:
    branches: '*'

jobs:
  quality:
    name: "Quality: ${{ matrix.node-version }} ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: "Set node version to 18"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: "Install deps: ${{ matrix.node-version }} ${{ matrix.os }}"
        run: pnpm install

      - name: "Check: ${{ matrix.node-version }} ${{ matrix.os }}"
        run: pnpm run check:type && pnpm run check:script && pnpm run check:format

      - name: "Format: ${{ matrix.node-version }} ${{ matrix.os }}"
        run: pnpm run format2

      - name: "Build: ${{ matrix.node-version }} ${{ matrix.os }}"
        run: pnpm run build

      # Uncomment this section if you want to check formatting
      # - name: Check formatting
      #   run: pnpm prettier --check .
